line-length = 200
target-version = "py311"

[lint]
select = [
    "E",   # pycodestyle errors (includes E402 - module import not at top)
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "C90", # mccabe complexity
]
ignore = [
    "E501",  # line too long (handled by formatter)
]

fixable = ["ALL"]
extend-unsafe-fixes = ["E402", "B904"]

[lint.pydocstyle]
convention = "google"

[lint.isort]
force-single-line = false
combine-as-imports = true
split-on-trailing-comma = true
known-first-party = ["src"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.pylint]
max-args = 10
max-branches = 15
max-returns = 8
max-statements = 60

[format]
quote-style = "double"
indent-style = "space" 
line-ending = "auto"
skip-magic-trailing-comma = true
